# Generated by Django 3.2.15 on 2022-08-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellProduct',
            field=models.IntegerField(default=0),
        ),
    ]
